### ISSUE TITLE
TclError: bad window path name ".!registration_user.!vkeyboard"

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#11]
@WK-GiHu, sir, I've put 2 `py files` in `codes` named 

- `register_user.py` 
- `Kiosk.py` 

this error is quite similar to the previous one since it's not altering how my main program works. I have 

- a `start page` there's a 
  - login button there. 
    after login I'll proceed to main menu, which is there's a lot of buttons. 

- When I'm clicking the back button, there's no error. 
- If I clicked the `register user` the button is calling a `registration module` 
  - after typing some and go back to `main page` 
  - then if i clicked `back to login` again, 
    it's showing me this error. 
    but when I didn't clicked the `register user` and just clicked the `back to login` there's no error.
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/Thesis/VKeyboard.py", line 41, in on_event
    super().withdraw()
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1995, in wm_withdraw
    return self.tk.call('wm', 'withdraw', self._w)
_tkinter.TclError: bad window path name ".!registration_user.!vkeyboard"
```

_Originally posted by @Justinjay282 in https://github.com/Justinjay282/qwerty/issues/9#issuecomment-585201034_

**Comment by WK-GiHu** [comment]
@Justinjay282 

### REVIEW `Kiosk.py`
You have remove `VKeyboard(self)` in `class Kiosk`, ***WHY***?

---

>.TclError: bad window path name ".!registration_user.!vkeyboard"

This error means your `class Registration_User` is deleted, but the `VKeyboard.bind_all` is still active...

For now, I think bring back `VKeyboard(self)` into `class Kiosk` and **don't** add it into `class Registration_User`.

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I did what you've said but it's opening the `VKeyboard` on the wrong position.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>TclError: bad window path name ".!registration_user.!vkeyboard"

If the topic **Issue** is fixed, please close this issue

**Comment by Justinjay282** [comment]
@WK-GiHu, I'll close this since it has been solved by moving the `VKeyboard(self)` to `main.py`
