### ISSUE TITLE
opening the `VKeyboard` on the wrong position.

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#12]
@WK-GiHu, sir, I did what you've said but 

- it's opening the `VKeyboard` on the wrong position. 
  - this is also the issue I'm encountering when I put entries on a `toplevel` window. 

It's always opening 
-  on top, 
-  not on the right position we've set in `VKeyboard.py`

_Originally posted by @Justinjay282 in https://github.com/Justinjay282/qwerty/issues/11#issuecomment-585215816_

**Comment by WK-GiHu** [comment]
@Justinjay282 

>it's opening the VKeyboard on the wrong position. 

I  have
https://github.com/Justinjay282/qwerty/blob/315c1c72f067d6509421ced3e9f5845f3fe21a63/VKeyboard.py#L13

verify if you have this also in your running vesion

**Comment by Justinjay282** [comment]
@WK-GiHu, yes sir, I also have it. The wrong position of the `VKeyboard1` is at both x and y is 0. at the top left edge of the screen.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>I also have it. 

Does it work before?
- [ ]  Yes
- [ ]  No


Is the `background="cornflowerblue"` the correct color?
- [ ]  Yes
- [ ]  No

**Comment by Justinjay282** [comment]
`print(self.wm_geometry())` = `<bound method Wm.wm_geometry of <__main__.VKeyboard object .!vkeyboard>>` I printed it in `VKeyboard`

**Comment by Justinjay282** [comment]
@WK-GiHu, 
> Does it work before?
It's working if I declare the `VKeyboard` in `register_user` but I got the error ```TclError: bad window path name ".!registration_user.!vkeyboard"``` when I opened the `register button`. If I declare the `VKeyboard` in `Kiosk.py` which is the main code. It's opening in the wrong position but the error is gone.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>`<bound method Wm.wm_geometry of <__main__.VKeyboard object .!vkeyboard>>`

Look not like the expected output, should be: `1x1+0+283`
Are you sure you have used: `print(self.wm_geometry())`?

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, sorry my mistake. I mistyped and put `print(self.wm_geometry)` instead of `print(self.wm_geometry())` It did output what you've expected.

**Comment by Justinjay282** [comment]
@WK-GiHu, I printed it in `VKeyboard.py`

**Comment by WK-GiHu** [comment]
@Justinjay282 

>It did output what you've expected. `1x1+0+283

I clearly states the coordinates `x=0` which is left border of the screen and `y=283` which is `283` pixel from the top screen border.

Verify if you have **another** `geometry` statement in `VKeyboard.py`

---

>It's working if I declare the `VKeyboard` in `register_user`

The only difference ist you dont declare the `parent` which default to `None`
Pleas update both files: `Kiosk.py` and `register_user.py`

**Comment by Justinjay282** [comment]
@WK-GiHu,sir, `self.geometry("+0+283")` is the only geometry in `VKeyboard.py`. `Vkeyboard.py`, `Kiosk.py` and `register_user.py` has been updated

**Comment by Justinjay282** [comment]
@WK-GiHu,sir, I put `VKeyboard(self)` to `Kiosk.py` and remove `VKeyboard(self)` from `register_user`

**Comment by WK-GiHu** [comment]
@Justinjay282 

1. Cleanup your import statements as described here: https://github.com/Justinjay282/qwerty/issues/13

2. Change to
https://github.com/Justinjay282/qwerty/blob/5aac275720b6b628074e0bafb96423d7eedf41bd/register_user.py#L8
    ```
    def __init__(self, parent):
        super().__init__(parent)
    ```
3. Change to
https://github.com/Justinjay282/qwerty/blob/5aac275720b6b628074e0bafb96423d7eedf41bd/Kiosk.py#L61
    ```
    register_user.Registration_User(self)
    ```

**Comment by Justinjay282** [comment]
@WK-GiHu, I still got the same result, sir.

**Comment by WK-GiHu** [comment]
@Justinjay282 

Did you running this `VKeyboard.py` as shown here?
And you claim it displays at `x=0/y=0`

**Comment by Justinjay282** [comment]
@WK-GiHu, yes sir. It displayed at `x and y =0` instead of `x=0, y=283`.

**Comment by WK-GiHu** [comment]
@Justinjay282 

Did you run the exact same `VKeyboard.py` as shown here?
Tell the pixel size of your screen

**Comment by Justinjay282** [comment]
@WK-GiHu but it's displaying correctly if I declare the `VKeyboard(self)` in `register_user`

**Comment by Justinjay282** [comment]
@WK-GiHu, it's 1920x080

**Comment by WK-GiHu** [comment]
@Justinjay282 

### PLEASE, answer my question
Did you run the exact same VKeyboard.py as shown here?

---

>but it's displaying correctly if I declare the VKeyboard(self) in register_user

I noted this, **but it makes no sense**.

**Comment by Justinjay282** [comment]
> @Justinjay282
> 
> ### PLEASE, answer my question
> Did you run the exact same VKeyboard.py as shown here?
> 
> > but it's displaying correctly if I declare the VKeyboard(self) in register_user
> 
> I noted this, **but it makes no sense**.

yes sir, I did run the `VKeyboard.py` shown here.

**Comment by WK-GiHu** [comment]
@Justinjay282 

Upate the files here, i want to review.
I still feel it has to do with the `import ...` sequence.

> run the VKeyboard.py shown here.

Ok, run it now standalone, not from `Kiosk.py` or `register_user.py` and report the result.

**Comment by Justinjay282** [comment]
> Ok, run it now standalone, not from `Kiosk.py` or `register_user.py` and report the result.
>
Done and it's output was the correct position of the `Virtual keyboard` Is it okay if I put my original code in the repository?

**Comment by WK-GiHu** [comment]
@Justinjay282 

> output was the correct position of the Virtual keyboard

OK, now we have to find the reason why it fails if `imported ...`

---

>Is it okay if I put my original code in the repository?

Yes, if it does not include any secrets.

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I've just updated the `Kiosk.py` and the `register_user`

**Comment by WK-GiHu** [comment]
@Justinjay282 

>updated the Kiosk.py

OK, unfortunatly you don't have any entry in `Kiosk.py`, i want to test without running `register_user.py` first.
Please add at the the two widgets `Entry` and `Button` from `VKeyboard.py.__main__` into `Kiosk.py.__init__` and verify the position.

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, it's in the correct position if I put an entry on `Kiosk.py`

**Comment by Justinjay282** [comment]
@WK-GiHu, I tried to click on the entry I created in `Kiosk.py` it positioned correctly. I then clicked the login and proceed to `register user` and it's position correctly. If I proceed to login immediately and then click the `register_user` it's position is wrong, but if I clicked the entry first on the `Kiosk.py` then proceed to login it's position is correct.

**Comment by WK-GiHu** [comment]
@Justinjay282 

> it's in the correct position if I put an entry on Kiosk.py

>I tried to click on the entry I created in Kiosk.py it positioned correctly. I then clicked the login and proceed to register user and it's position correctly. If I proceed to login immediately and then click the register_user it's position is wrong, but if I clicked the entry first on the Kiosk.py then proceed to login it's position is correct.

OK, i have to rethink about this.
I have to go offline now, will continue later

**Comment by Justinjay282** [comment]
@WK-GiHu, I added `.geometry(...` before line 38 and it's working now like magic. thank you so much sir :)

**Comment by Justinjay282** [comment]
Take a rest now sir and thank you so much :) I'll rest too and then continue my thesis to find if there's any error or loop hole I can get in my program. Thank you so much!

**Comment by WK-GiHu** [comment]
@Justinjay282 

>I added .geometry(... before line 38 and it's working now

OK, but still can't explain ...
Close this Issue if the topic are solved
