### ISSUE TITLE
import statement order

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#13]
@Justinjay282 

Reorder your import statements as following:
```
from tkinter import *
from tkinter import messagebox
from tkinter import ttk
from PIL import Image, ImageTk
from VKeyboard import VKeyboard
import register_user
import pymysql
```

You are using `from tkinter import *`, avoid `*` import statements.
Use the common one:
```
import tkinter as tk
import tkinter.ttk as ttk
```
This requires to prefix all used `tkinter` attributes with `tk`, e.g. `tk.Button(...`

**Comment by Justinjay282** [comment]
@WK-GiHu, noted sir. I will change my import statements. from `from tkinter import *` to `import tkinter as tk`

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, can I ask how to change the letters to capital when I clicked `Caps Lock`? It's inputting a capital but not showing capital letters on my virtual keyboard.
