### ISSUE TITLE
`combobox` with a list of purposes.

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#16]
I've created a `combobox` with a list of purposes. 

The last one on the list is `"Others"` If I clicked `"Others"` on my purpose then a `label` and an `entry` will appear. 

Should I use, `var.trace(callback)` ? 

I will also do the same with the calendar. I've created a drop-down calendar if I select a month with 30 days the `combobox` will show 30 days only

_Originally posted by @Justinjay282 in https://github.com/Justinjay282/qwerty/issues/15#issuecomment-587275735_

**Comment by WK-GiHu** [comment]
@Justinjay282 

>Should I use, `var.trace(callback)` ?

Bind to the `"<<ComboboxSelected>>"` event.
Read [how-to-make-a-ttk-combobox-callback](https://stackoverflow.com/questions/35209522)

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I understand this thank you so much :)
