### ISSUE TITLE
scan a fingerprint or RFID without choosing any login option 

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#18]
sir @WK-GiHu, he didn't say anything because he's mad at us. He said he wants most of our system to change. He wants us to create a flash if our RPI is not on use, the system will flash an announcement, plans, etc. He also wants us to remove the limitation of our fingerprint but it's out of my ability... He said he wants our system to scan a fingerprint or RFID without choosing any login option (I don't have any idea how I will do it but I'll still try...) we have to finish all the system by next week so we can proceed to our evaluation and chapter 4... I did a lot of changes I'm searching now on how to make things work out on our system... Can you give me an idea sir, on how I will do some of these, especially the RFID and Fingerprint scanner is running simultaneously? If I scan RFID or finger either of the two I will proceed to the main page. Also, in flash screen or splash screen whatsoever, it will only pop out if the RPI or kiosk is on an idle state or if no one is using it and if a person didn't log out his account. after a couple of seconds, it will go back to the login page. I'll study it even if I didn't get enough sleep...

_Originally posted by @Justinjay282 in https://github.com/Justinjay282/qwerty/issues/17#issuecomment-589077179_

**Comment by WK-GiHu** [comment]
@Justinjay282 

>scan a fingerprint or RFID without choosing any login option 

In general you have to run `fingerprint` and `RFID` in a own `thread` or own `Process`.
Read [threading.Thread](https://docs.python.org/3/library/threading.html#threading.Thread)

Example:
```
import threading

class FingerprintThread(threading.Thread):
    def __init__(self, app, callback)
        super().__init__()
        self.app = app
        self.app.bind('<<GRANT_ACCESS>>', callback)
        self.start()

    def run(self):
        # Run forever
        while True:
             # listen to the Finger Reader
            fingerprint = finger_reader.get()
             # process fingerprint
             if <is valid fingerprint>:
                 self.app.event_generate('<<GRANT_ACCESS>>', when='tail')

class Kiosk(tk.Tk):
    def __init__(self)
        ...
        FingerprintThread(self, callback=self.on_grant_access)

    def on_grant_access(self, *event):
        # Received a valid Fingerprint or RFID
        # show main screen
        self.deiconify()
```

**Comment by Justinjay282** [comment]
Hi sir @WK-GiHu, so I need to create two `classes`? `class FingerprintThread(threading.Thread):` and `class RFIDThread(threading.Thread)`? then I will call both on my `def __init__(self)`? On my current code, I didn't use this obviously that's why the whole GUI is freezing when the RFID or Fingerprint is running, I used `event` `varname.bind("Enter", callback)` do I need to use it in this?

**Comment by WK-GiHu** [comment]
@Justinjay282 

>so I need to create two classes? class FingerprintThread(threading.Thread): and class RFIDThread(threading.Thread)? then I will call both on my def __init__(self)? On my current code, I didn't use this obviously that's why the whole GUI is freezing when the RFID or Fingerprint is running, 

Yes, read [use threads to preventing main event loop from “freezing”](https://stackoverflow.com/a/16747734/7414759)

>I used event varname.bind("Enter", callback) do I need to use it in this?

Can't get what you want to accomplish with this statement.
Explain in more detail and/or provide a link to your source.

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, can you check what I've been doing so far. I put it it `repository` named `Kiosk_main.py` Thank you so much

**Comment by WK-GiHu** [comment]
@Justinjay282 

**Review `Kiosk_Main.py`**

**Note**: Distinguish between `__main__ Thread` and `background Thread`.
  - The class method `__init__` get executed in the `__main__ Thread` https://github.com/Justinjay282/qwerty/blob/401b61868084aea93af42c59c5360816af44089b/Kiosk_Main.py#L10

- The class method `run` get executed in the new started `background Thread` https://github.com/Justinjay282/qwerty/blob/401b61868084aea93af42c59c5360816af44089b/Kiosk_Main.py#L18

---

- [ ] The initalisation of `mysql` have to be inside the `background Thread`.
  https://github.com/Justinjay282/qwerty/blob/401b61868084aea93af42c59c5360816af44089b/Kiosk_Main.py#L14-L16

---

- [ ] The following code block belongs to initalisation of `PyFingerprint` and have to be done **once**.
 Therefore it have to be outside the **run forever** `while True:`
https://github.com/Justinjay282/qwerty/blob/401b61868084aea93af42c59c5360816af44089b/Kiosk_Main.py#L20-L32

---

- [ ] Multiple calling of `self.cursor.execute(...` is double work, as `fetchone()` returns alle the fields allready when you use `SELECT * ...`!

  Do a `print(self.cursor.fetchone())` to see what you get.
  https://github.com/Justinjay282/qwerty/blob/401b61868084aea93af42c59c5360816af44089b/Kiosk_Main.py#L52

---

- [ ] You didn't start ` FingerprintThread` yet.

---

- [ ] Insert a trace `print('Kiosk.on_grant_access()')` to see if you get the event `<<GRANT_ACCESS>>`
 There is a typo in line L153
 https://github.com/Justinjay282/qwerty/blob/401b61868084aea93af42c59c5360816af44089b/Kiosk_Main.py#L151-L153

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I tried to print the `self.cursor.fetchone()` but I can't get the value maybe because it's not running. and `print(Kiosk.on_greate_access())`since it's also not printing I tried `self.on_grant_access()` but I'm receiving an error 
```

Traceback (most recent call last):
  File "/home/pi/Thesis/Thesis_Revised.py", line 1721, in <module>
    Kiosk().mainloop()
  File "/home/pi/Thesis/Thesis_Revised.py", line 181, in __init__
    self.on_grant_access()
  File "/home/pi/Thesis/Thesis_Revised.py", line 183, in on_grant_access
    print(Kiosk.on_grant_access())
TypeError: on_grant_access() missing 1 required positional argument: 'self'
```

**Comment by WK-GiHu** [comment]
@Justinjay282 

- [ ] I removed **ALL** checkmarks from https://github.com/Justinjay282/qwerty/issues/18#issuecomment-589648876. You didn't fulfill **any** advise. please read carefully again and try again. 

---

**Review `Kiosk_Main.py`**

- [ ] As it stands it will fail with `Undefined Error: undefined attribute 'f'`
  https://github.com/Justinjay282/qwerty/blob/d240a0a072356deb1d8405f01adf384299e7b309/Kiosk_Main.py#L32

>I tried to print the `self.cursor.fetchone()` but I can't get the value maybe because it's not running.

- [ ]  As it stands it will fail with `Undefined Error: object FingerprintThread undefined attribute 'cursor'`.
  https://github.com/Justinjay282/qwerty/blob/d240a0a072356deb1d8405f01adf384299e7b309/Kiosk_Main.py#L44

- [ ] Unrelated to the above, `Undefined Error`, you have to change the following codeblock

  https://github.com/Justinjay282/qwerty/blob/d240a0a072356deb1d8405f01adf384299e7b309/Kiosk_Main.py#L45-L47
  ```
    result = self.cursor.fetchone()
    print(result)
    if result:
        ...
  ```

---

>`print(Kiosk.on_greate_access())` since it's also not printing I tried `self.on_grant_access()` but I'm receiving an error

It's a typo, copy exact my `print(...` statement, you don't have to call anything only print a trace info as string.

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I edited my code. Sorry, I misunderstood it since I'm very sleepy... I just want to ask if the `background Thread` is the `FingerprintThread`? I didn't check the declaration of connection of the database coz I'm not so sure where I willput it... and how can I start the `FingerprintThread`? I jsut called it in my `class Kiosk` by typing `FingerprintThread(self, callback = self.on_grant_access)` I'm really sorry if I'm such a headache...

**Comment by WK-GiHu** [comment]
@Justinjay282 

> just want to ask if the background Thread is the FingerprintThread? 

- [ ] The `class FingerprintThread` starts a new `Thread`.
Read again my **Note** at : https://github.com/Justinjay282/qwerty/issues/18#issuecomment-589648876

>I didn't check the declaration of connection of the database coz I'm not so sure where I willput it... 

- [ ] Move it into `def run(...`, same as `PyFingerprint ...`

>and how can I start the FingerprintThread? 

This instantiate the `class FingerprintThread`, see https://github.com/Justinjay282/qwerty/issues/18#issuecomment-589167004 how to start.

>I jsut called it in my class Kiosk by typing 
>`FingerprintThread(self, callback = self.on_grant_access)` 
>the `print('Kiosk.on_grant_access()')` got printed

- [ ] Remove Line 150, you don't have to call this callback by yourself.
  It have to be called by `.event_generate(...`
  https://github.com/Justinjay282/qwerty/blob/2ecf71d5f4a8ad046f672e274166a00ae16085f1/Kiosk_Main.py#L150

**Comment by Justinjay282** [comment]
sir @WK-GiHu, it's working not. It's running even if I don't have a button. Thank you so much. I will do the same to RFID right sir? I will do it now. I'm sorry if I misunderstood lots of things. I'm really lack of sleep but I will do my best. I will post my attempt in RFID sir.

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I edited the code and added the `RFIDThread(threading.Thread)`

**Comment by WK-GiHu** [comment]
@Justinjay282 

>it's working not. It's running even if I don't have a button. 

Didn't understand this, please explain in detail.
Which `Button`?

>I will do the same to RFID right sir? I will do it now. 

Wait until `FingerprintThread` works.

>I have registered fingerprint but the messagebox is popping out and saying Not yet registeredbut the I have the printed out value of print(result) from database.

You still using `.fetchone()`, but you can call `.fetchone()` only once:
https://github.com/Justinjay282/qwerty/blob/78c09bee74daf511f5df699f61b23508ad7b20ad/Kiosk_Main.py#L49

### Read again still not fulfilled: https://github.com/Justinjay282/qwerty/issues/18#issuecomment-589701861

---

- [ ] Still a typo here
  https://github.com/Justinjay282/qwerty/blob/78c09bee74daf511f5df699f61b23508ad7b20ad/Kiosk_Main.py#L256-L259

**Comment by Justinjay282** [comment]
@WK-GiHu, sir. I've edited the code in `repository`
> * [ ]  Still a typo here
>   https://github.com/Justinjay282/qwerty/blob/78c09bee74daf511f
I just want to clarify this
is it. `print('Kiosk.on_grant_access()') or `print(Kiosk.on_grant_access())`

**Comment by Justinjay282** [comment]
> @Justinjay282
> 
> > it's working not. It's running even if I don't have a button.
> 
> Didn't understand this, please explain in detail.
> Which `Button`?

Sir @WK-GiHu , I'm sorry, I mean it's working now. I'm printing a value from the database. but I'm not proceeding to the main page

**Comment by WK-GiHu** [comment]
@Justinjay282 

> I mean it's working now. 

OK


>I'm printing a value from the database. 

- [ ] Make `result` a class attribute.
  https://github.com/Justinjay282/qwerty/blob/0b43ed964fbae9015535d7db0b9e293b4c93e157/Kiosk_Main.py#L48
  ```
  self.result = self.cursor.fetchone()
   ```

- [X] Multiple calling of `self.cursor.execute(...` is double work, as `fetchone()` returns alle the fields allready when you use `SELECT * ...`!
  - [ ] Now, get rid of all multiple `self.cursor.execute(...` and `... self.cursor.fetchone()`.

  https://github.com/Justinjay282/qwerty/blob/0b43ed964fbae9015535d7db0b9e293b4c93e157/Kiosk_Main.py#L51

---

>but I'm not proceeding to the main page

I didn't have the overview about your whole code/screen/page - flow
I feel, placing `FingerprintThread` into `class Kiosk` ist not OK, should be into the **first** `module/class/function` at startup. 

The goal should be:
1. start the program
2. prepare for callback
3. start the background `Thread`'s
4. wait on even `'<<GRANT_ACCESS>>'`
5. start/show the GUI
6. run program until exit
7. withdraw GUI
8. continue with 4.

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I've edited the code and remove the `fetchone()...` I've also included the main page to proceed if the login is successful. I also have an `if condition` and the data will be looked first in `residents_admin database` then to `residents_db database` if the I scanned a fingerprint and if it exists in `residents_admin` it will proceed to `def choose_admin` if the finger exists in `residents_db` it will proceed to `def choose_user` while the RFID, if there's an RFID registered in the database the security question will pop out the user will answer the `security question` and will also procceed to the `methods` I mentioned in `fngerprint login`. 

our adviser wants to show the GUI first. because in our first background of GUI there's a `SCAN THE FINGERPRINT OR RFID TO LOGIN` then if the finger or RFID is registered then it will proceed to what I've explained above.

**Comment by WK-GiHu** [comment]
@Justinjay282 


**Review `Kiosk_Main.py`**

- [ ] There is a typo
  https://github.com/Justinjay282/qwerty/blob/6304fd9550a4c7c858089074a15d61a0f8efbff0/Kiosk_Main.py#L49

---

>the RFID is working but when I scanned it's looping on messagebox.showerror("Notice!", Not yet registed") non-stop. 

Compare with `FingerprintThread`, there you have **two** sections within `def run(`
1. Initialize before `while True:`
2. Run forever inside the `while True:` block.

You didn't obey this in `RFIDThread`

---

>since I've two different paths to proceed after successful login do I need another def grant_access(...?

You can do so, but this requires a second event and `.bind(..`, e.g. `'<<GRANT_ADMIN_ACCESS>>'` also. 

My proposal, extend to:
```
self.app.event_generate(..., state=x, ...)
```

- [ ] `state=1` 
  https://github.com/Justinjay282/qwerty/blob/6304fd9550a4c7c858089074a15d61a0f8efbff0/Kiosk_Main.py#L52
- [ ] `state=2` 
 https://github.com/Justinjay282/qwerty/blob/6304fd9550a4c7c858089074a15d61a0f8efbff0/Kiosk_Main.py#L58

- [ ] in `def on_grant_access` do
  https://github.com/Justinjay282/qwerty/blob/6304fd9550a4c7c858089074a15d61a0f8efbff0/Kiosk_Main.py#L129
  ```
  if event.state == 1:   # residents admin
      ...
  elif event.state == 2:   # residents
     ...
  ```

---

>the variables I've set there is already in use.

Obey Issue: https://github.com/Justinjay282/qwerty/issues/21

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I've edited the code. The RFID loop has been fixed and working just like how `FingerprintThread` works.
I'm having a problem with `state` I have an error.
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/Thesis/Thesis_Revised.py", line 160, in on_grant_access
    if event.state == 1:
AttributeError: 'tuple' object has no attribute 'state'
```

**Comment by WK-GiHu** [comment]
@Justinjay282 

>AttributeError: 'tuple' object has no attribute 'state'

My bad, remove the leading `*`, should read `def on_grant_access(self, event)`
https://github.com/Justinjay282/qwerty/blob/9c9efd7c64f5827ac71202763a4bc78d540a8cf7/Kiosk_Main.py#L151

---

Do you realy need a own callback `def on_grant_access` here?
https://github.com/Justinjay282/qwerty/blob/9c9efd7c64f5827ac71202763a4bc78d540a8cf7/Kiosk_Main.py#L159

**Comment by Justinjay282** [comment]
> Do you realy need a own callback `def on_grant_access` here?
> https://github.com/Justinjay282/qwerty/blob/9c9efd7c64f5827ac71202763a4bc78d540a8cf7/Kiosk_Main.py#L159

sir, @WK-GiHu , I just put it there coz I don't know where it will proceed if the RFID login is successful.

**Comment by Justinjay282** [comment]
sir, @WK-GiHu, it's working now. I still have a problem... the RFID scanner is running non-stop so it's scanning a lot of times. how can I make it scan 1 at a time? It's working now. I just need to pass the variable values to proceed to log in.

**Comment by WK-GiHu** [comment]
@Justinjay282 

**Update the file, so i can review**

>What I need to do is to get the value of the result, I can do result[0], result[1] and so on ... right?

Yes, or simple use the `def update_vars` with the correct predefined `Residents = ...`
See review: https://github.com/Justinjay282/qwerty/issues/21

**Comment by Justinjay282** [comment]
sir, @WK-GiHu, I just updated the file. I think I have a problem with `def on_grant_access_RFID` if I scanned an RFID or Fingerprint It's proceeding to `def on_grant_access_RFID` should I remove the `def on_grant_access_RFID`? Will it work if I just do,
``` 
def on_grant_access(self, event):
    if state == 1:
        ... #admin main page
    if state == 2:
        ... #user main page
    if state == 3:
        ... #admin security question
    if state == 4:
        ... #user security question
```
and will changed the `RFID login` `self.app.event_generate(..., state = 3,...)`?

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I tried the statement above^ I think it's working. Now I'm just clueless on how can I get the value of `self.result` to `class Kiosk` sir. I also need to pass the `self.id` but not the `Finger Template`

**Comment by WK-GiHu** [comment]
@Justinjay282 

>the fingerprint should proceed to def on_grant_access

You can't use the same event, here `'<<GRANT_ACCESS>>'` to bind to different callback functions.
The last one overwirtes the previous one.
Therefore you need the option argument `add='+'`

>Will it work if I just do, ... and `.event_generate(..., state = 3,...) ..., state = 4, ...)`

Yes, i suggest to use `state11` and `state=12`

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I've just edited the code. I removed the `def on_grant_access_RFID` and the `def on_grant_access` remains. I added the `if state == 11:... and if state ==12 ...` 
I just have to get the value of `self.result` and `self.id`

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I tried `RFIDThread.result` to get the value but I'm receiving an error...

**Comment by WK-GiHu** [comment]
@Justinjay282 

>I tried `RFIDThread.result` to get the value but I'm receiving an error...

Therefore you need a `reference` or a `class variable`.

1. Solution `class variable`
  ```
   class RFIDThread:
       result = None  # <= this is a class variable

       def run(self):
          ...
          RFIDThread.result = self.cursor.fetchone()
  ```
2. Solution `reference`
  ```
  class Kiosk(tk.Tk):
    def __init__(self):
        ...
        self.ref_to_class_rfid = RFIDThread(...
  ```
  **Usage**
  ```
  # outside Kiosk
  print(<ref to Kiosk>.ref_to_class_rfid.result)

  # inside Kiosk
  print(self.ref_to_class_rfid.result)
  ```

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I think it's working now. Thank you so much! I've edited the code in repository. If you want to review sir to tell if I did all correctly. with `result = self.cursor.fetchone()` I can also get a `blob` right? Because I also want to get a picure to display on my main page. I'll try to do the splash window later after some rest. I think i can get some sleep today since you really help me move a very big progress. Thank you so much sir

**Comment by WK-GiHu** [comment]
@Justinjay282 

>with `result = self.cursor.fetchone()` I can also get a blob right?

I think so, it's a object in the `result` tuple.

---

**Review `Kiosk_Main.py`**

You **can't use both** solutions.
As you assign to ` RFIDThread.result = self.cursor.fetchone()` you don't get the `result` by doing `self.ref_to_class_finger.result`.

**You have to make a decision**:
- [ ] `class variable`
- [ ] `class instance variable`

---

https://github.com/Justinjay282/qwerty/blob/901d031ba9ac6c0649ad4a1326ead01e1f46f506/Kiosk_Main.py#L137

Add a condition to distinguish between `finger` and `rfid`
```
if event.state < 10:  # finger
    # print finger result
else:  # rfid
    # print rfid result
```

**Comment by Justinjay282** [comment]
sir, @WK-GiHu, I've edited the code. I deleted the `class instance variable` and choose `class variable` then I used in `def on_grant_access(self, event)` the `print(FingerprintThread.result)` also added the condition you proposed above.
