### ISSUE TITLE
class SplashThread(threading.Thread) in Kiosk_main.py

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#23]
@WK-GiHu, I'm thinking of it until now... I'm sorry if I'm very slow on this...  I did some revisions. I put `self.event_generate('<<IDLE>>', state = 0, when = 'tail')` to `VKeyboard.py` and added `class SplashThread(threading.Thread)` in `Kiosk_main.py`

_Originally posted by @Justinjay282 in https://github.com/Justinjay282/qwerty/issues/19#issuecomment-590074805_

**Comment by WK-GiHu** [comment]
@Justinjay282 

>class SplashThread(threading.Thread) in Kiosk_main.py

I think it will complicationg things if you combine `Splash` with `Counter Thread`.
The `class Splash` should be a `Frame/Toplevel Window`.
Didn't you have it allready?
The `Counter` **must** be a `Thread`!

You have to make a decision:
- [ ] I want to combine `Splash` with `Counter Thread`.
- [ ] I will continue with **two** objects, 
  1. `Splash`
  2. `CounterThread`

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, thank you for always clarifying me things. As it's really hard for me, I have to avoid the complication of my code since it will get harder for me to understand. I just got confused about `Counter` and create `class SplashThread`. Does this mean I don't have to create a `class splash` inside the `Kiosk_main.py`? and then create the `counter` inside the `VKeyboard.py` by having another `class`? eg. `class Counter(threading.Thread):`?

**Comment by WK-GiHu** [comment]
@Justinjay282 

>I just got confused about Counter and create class SplashThread

Stop, for now, thinking about `Splash`.
Focus on the `Counter`

>have to create a class splash inside the Kiosk_main.py?

Depends on how you call the `Splash` screen, i think you can do so

**Didn't you have allready a Splash screen?**
- [ ] Yes
- [ ] No

---

>and then create the counter inside the VKeyboard.py by having another class? eg. class Counter(threading.Thread):?

Yes, you can do so.
I recommend to use a own module, which allows simpler testing.
Extend the name to something meaningfull, like `IdelCounter` or `IdleWatchdog` ...

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I've edited the `Keyboard.py` in `repository` I've added the following:
```
class idleCounter(threading.Thread):
    def __init__(self, app, callback):
        super().__init__()
        self.app = app
        self.app.bind('<<IDLE>>', callback)
        self.start()

    def on_idle(self, event):        
        if event.state == 0:  # reset the counter
           self._counter = self. timeout
           splash = Toplevel()
           #GUI HERE
        self.deiconify()
```
and in `class VKeyboard __init__` I put the `self.event_generate('<<IDLE>>', state =0, when = 'tail')`

**Comment by WK-GiHu** [comment]
@Justinjay282 

https://github.com/Justinjay282/qwerty/blob/aa1aff61e3dfabc999cef3c29552789f12262fa3/VKeyboard.py#L4-L9

- [ ] Please use uppercase `'I'`by naming a `class`
- [ ] Here you don't need a ouside `callback`, remove it, your `callback` is your own `def on_idle(...`

---

https://github.com/Justinjay282/qwerty/blob/aa1aff61e3dfabc999cef3c29552789f12262fa3/VKeyboard.py#L11-L16

- [ ] Where do you think is `self. timeout` defined?
  This will fail with `Attribute Error` 

- [ ]  Remove it, no GUI within this class
  Revmove it =>    `splash = Toplevel()`
  Revmove it =>    `#GUI HERE` 
  Revmove it =>    `self.deiconify()` 

- [ ] MISSING, the background `Thread`, read again: https://github.com/Justinjay282/qwerty/issues/18#issuecomment-589648876

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I've committed the changes in `Keyboard.py`.
>Where do you think is self. timeout defined?
This will fail with Attribute Error

is it defined in `background Thread`...?
