### ISSUE TITLE
Implementation of class IdleCounter

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#24]
https://github.com/Justinjay282/qwerty/blob/3a61cbbd86e3471c969964771184940a1603df54/VKeyboard.py#L4-L26

**Comment by WK-GiHu** [comment]
@Justinjay282 

- [ ] Here you don't need a ouside `callback`, remove it, your `callback` is your own `def on_idle(...`
  - [ ] Remove it from the `__init__` argument list.
  - [ ] Read the above again ***"your `callback` is ..."***

---

- [ ] Where do you think is `self. timeout` defined?
  This will fail with `Attribute Error` 

  >is it defined in background Thread...? https://github.com/Justinjay282/qwerty/issues/23#issuecomment-590091028
  
  That's possible, the propper way is to define it in `__init__`.
  - [ ] What do you think the variable `self.timeout` is for.

---

- [ ] This will fail with `Attribute Error`, the `class IdleCounter` does not have a method `.deiconify()`. Implement the counter instead here.
https://github.com/Justinjay282/qwerty/blob/ad85817f32515de0d858b0e0de0448e1f9d7bf83/VKeyboard.py#L12

**Comment by Justinjay282** [comment]
sir, @WK-GiHu.
>   * [ ]  What do you think the variable `self.timeout` is for.
>

I think the `self.timeout` is a trigger to reset the counter right? I mean is it set to 0? since it's for the counter to reset...

> * [ ]  This will fail with `Attribute Error`, the `class IdleCounter` does not have a method `.deiconify()`. Implement the counter instead here.
>   https://github.com/Justinjay282/qwerty/blob/ad85817f32515de0d858b0e0de0448e1f9d7bf83/VKeyboard.py#L12

by counter sir, is it the .after()? e.g. `var_name.after(2000, method)` ? or it's different than this?

**Comment by WK-GiHu** [comment]
@Justinjay282 

- [ ] Still not fulfilled https://github.com/Justinjay282/qwerty/issues/24#issuecomment-590117974
>> - [ ]  What do you think the variable self.timeout is for.
>
>I think the self.timeout is a trigger to reset the counter right? 
>Therefore, is it set to 0? since it's for the counter to reset...

Yes it's for the counter to reset, but we want to implement a **count down** counter.
How will the counter count down if set to `0`?

---

>by counter sir, is it the .after()? e.g. var_name.after(2000, method) ? or it's different than this?

We are using a `Thread`, therefore **no** `tkinter.after(...`
Do, 
**Note**: Have verify myself if this will work!
```
   self._is_alive = threading.Event()
   self._is_alive.set()

   while self._is_alive.wait(1)::
       if self.counter > 0:
           self._counter -= 1
           if self._counter == 0:
               self._is_alive.clear()
               .event_generate('<<TIMEOUT>>',  when='tail')
```

**Comment by Justinjay282** [comment]
sir, @WK-GiHu, I've committed changes in `VKeyboard.py` It still has a lot of things to be done... I'm sorry if you're helping me so much but it seems like I can't even help myself... I did understand what we did in `FingerprintThread` and `RFIDThread` but I'm seriously confused by this... I'm so sorry, I think I'm hopeless...

**Comment by WK-GiHu** [comment]
@Justinjay282 

- [ ] A typo of me, should read `if self._counter > 0: `, note the underscore!
https://github.com/Justinjay282/qwerty/blob/3a61cbbd86e3471c969964771184940a1603df54/VKeyboard.py#L18

OK, but have to be done **before** `.start()`
https://github.com/Justinjay282/qwerty/blob/3a61cbbd86e3471c969964771184940a1603df54/VKeyboard.py#L11

Now at last you have  to assign values to it.

**Comment by Justinjay282** [comment]
@WK-GiHu, sir.

Now at last you have to assign values to it.

I've set the self._counter = 20
but literally not so sure about self.timeout... if def on_idle will reset the count down, then self.timeout has the same value as self._counter? I'm sorry I though I'me creating a new comment, I clicked your comment and edited it. I returned it back to normal im sorry.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>self.timeout has the same value as self._counter?

The opposite takes place, `self.timeout` is the constant value which get set to `self._counter`.

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, what do you mean by the **opposite takes place**? the `self.timeout` will get set to `self._counter` on `def on_idle` right? then, the isn't it both `self.timeout` and `self._counter` have the same value since the `def on_idle` is resetting the `self._counter`?

**Comment by WK-GiHu** [comment]
@Justinjay282 

>what do you mean by the opposite takes place?

You wrote: ***then self.timeout has the same value as self._counter?***
I wrote: ***self._counter = self.timeout***, because `self.timeout` is the constant value.

Doing
https://github.com/Justinjay282/qwerty/blob/23ffcf346db6fa05d2532683ce3a4f927fc23399/VKeyboard.py#L8-L9

is OK for now, it's semantic only.

---

See my `[PullRequest]`, merge it and run it

**Comment by Justinjay282** [comment]
sir, @WK-GiHu, I've merged and run it. It's working count down from 4 to 0 then if I clicked the `click to reset` it's going back to the countdown.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>It's working count down from 4 to 0 then if I clicked the click to reset it's going back to the countdown.

Is this your expected behavior?
If yes, you have to update your `class IdleCounter` accordingly because there are some changes.

**Comment by Justinjay282** [comment]
sir @WK-GiHu, Yes, I'm actually expecting that kind of behavior. I can just modify the RPI settings and I can just set it to `never sleep` so we will only rely on the timer if the `splash screen` will appear.

It's okay for me to have many changes, I only have 1 hr sleep and it's doesn't matter even if I am awake for more than 24 hrs. I am also more than willing to do the changes you want me to do. I will always be grateful for your help sir.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>It's okay for me to have many changes,

You can copy the whole `class IdleCounter` and remove disable the testing statements.

Next step, implement your `class SplashScreen`

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, this `class IdleCounter` is inside the `VKeyboard.py` right?

> Next step, implement your `class SplashScreen`

and this one is where GUI will appear? and it's inside of `Kiosk_Main.py`

**Comment by WK-GiHu** [comment]
@Justinjay282 

>and this one is where GUI will appear? and it's inside of Kiosk_Main.py
