### ISSUE TITLE
Implementation class SplashScreen

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#26]
@WK-GiHu, sir, this `class IdleCounter` is inside the `VKeyboard.py` right?

> Next step, implement your `class SplashScreen`

and this one is where GUI will appear? and it's inside of `Kiosk_Main.py`

_Originally posted by @Justinjay282 in https://github.com/Justinjay282/qwerty/issues/24#issuecomment-590372749_

**Comment by WK-GiHu** [comment]
@Justinjay282 

> this one is where GUI will appear? and it's inside of Kiosk_Main.py

Yes

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, the `IdleCounter` will also be in `Kiosk_Main.py` right? so our `VKeyboard` will back to its original code?

**Comment by WK-GiHu** [comment]
@Justinjay282 

>the IdleCounter will also be in Kiosk_Main.py right? so our VKeyboard will back to its original code?

### Doublecheck! You have overwritten [Kiosk_Main.py](https://github.com/Justinjay282/qwerty/blob/master/Kiosk_Main.py) with [VKeyboard.py](https://github.com/Justinjay282/qwerty/blob/master/VKeyboard.py)


You can do so, `class IdleCounter` it's only related to the `__main__ tk.Tk()`  object.
This becomes `self.app = app` in `__init__`.
You have to instantiate the `class IdleCounter` object by doing:
```
IdleCounter(<reference to the__main__ tk.Tk() object>)
```

---

>But I don't have an idea how will it appear after the coutdown.

See my testing `IdleCounter.py`:
The `class IdelCounter` sends a `'<<TIMEOUT>>'` event on timeout.
Therefore you have to bind this event to your function which will create the `Splash` screen.
https://github.com/Justinjay282/qwerty/blob/7981e9f2a12286e40d4f091a4b0ec39daeb83cd1/IdleCounter.py#L54
https://github.com/Justinjay282/qwerty/blob/7981e9f2a12286e40d4f091a4b0ec39daeb83cd1/IdleCounter.py#L65-L66

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I've edited the code in `repository` It is now successfully opening a `Splash Screen`. I just need to do if it was clicked it will disappear. Also, it is possible to insert content there from different class right?

**Comment by WK-GiHu** [comment]
@Justinjay282 

>I've edited the code

- [ ] This isn't bound and is not needed at all here, remove it.
https://github.com/Justinjay282/qwerty/blob/23bbb876dc1029a9d11514d839407a5c49f1353d/Kiosk_Main.py#L187

- [ ] Missing parameter `parent`, add argument `parent` to both lines
https://github.com/Justinjay282/qwerty/blob/23bbb876dc1029a9d11514d839407a5c49f1353d/Kiosk_Main.py#L140-L141

--

>It is now successfully opening a Splash Screen

OK!

---

>I just need to do if it was clicked it will disappear. 

This may interfere with `VKeyboard` so we have to disable `VKeyboard` temporaray?
Did the `VKeyboard` show up?

You have to bind the `<Button-1>` event to the `Toplevel` 
```
def on_button_click(self, event):
    print('SplashScreen.on_button_click')
    # Cleanup, unbind the `<Button-1>` event 
    # Reset IdleCounter
    self.destroy()
```

---

>Also, it is possible to insert content there from different class right?

You can insert what ever you want ...

**Comment by Justinjay282** [comment]
@WK-GiHu, sir I've committed the changes in `Main_Kiosk.py` I used `parent.bind_all('<Button-1>' self.on_click) in `SplashScreen __init__` It's now opening the `Splash Screen` after tapping, It's closing, but it's totally closed. and there's no countdown after that. Also, when the splash screen is closed everytime I click the code is printing `SplashScreen.on_button_click` and the `VKeyboard` is popping and typing normally .

**Comment by WK-GiHu** [comment]
@Justinjay282 

>I used parent.bind_all('<Button-1>' self.on_click) in SplashScreen __init__ It's now opening the Splash Screen after tapping, 

Change your `bind(...`
See my `[PullRequest]` testing `IdleCounter.py` for reference.


>It's closing, but it's totally closed. and there's no countdown after that. 

You don't fulfill the given comment: `Reset IdleCounter`


>Also, when the splash screen is closed everytime I click the code is printing SplashScreen.on_button_click and the VKeyboard is popping and typing normally .

You don't fulfill the given comment: `Cleanup, unbind the `<Button-1>` event`

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I've merged your `[PullRequest]` It's resetting the countdown and at the same time it's closing the `SplashScreen ` but when I click on my gui it's not resetting the count down. so it's always counting and after the countdown, the `SplashScreen will appear. even if I'm clicking and using the main GUI it's still popping up.I've edited the `Kiosk_Main.py` so you can review what edit I've made.

**Comment by WK-GiHu** [comment]
@Justinjay282 

Add avbove line 25 
```
print('IdleCounter.on_idle(state={})'.format(event.state))
```
https://github.com/Justinjay282/qwerty/blob/8eada18ae9a39f688a3757f1260ba9e5399c55e2/VKeyboard.py#L25

verify if you see this get printed at: ***if I'm clicking and using the main GUI***

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I've put it in ` def on_idle` but it's not printing.

**Comment by WK-GiHu** [comment]
@Justinjay282 

verify it this line is in place
https://github.com/Justinjay282/qwerty/blob/8eada18ae9a39f688a3757f1260ba9e5399c55e2/VKeyboard.py#L54

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, It's working now. But if the `class SplashScreen` was already opened. There's still a countdown. and after the countdown, it will open another `splashscreen`

**Comment by WK-GiHu** [comment]
@Justinjay282 

>There's still a countdown. and after the countdown,

While this happend, did you see the print of: 
https://github.com/Justinjay282/qwerty/blob/8eada18ae9a39f688a3757f1260ba9e5399c55e2/Kiosk_Main.py#L65

**Comment by Justinjay282** [comment]
@WK-GiHu, yes sir, It's printing the `print(`IdleCounter.on_idle(state = 0))`

**Comment by WK-GiHu** [comment]
@Justinjay282 

> It's printing the print(IdleCounter.on_idle(state = 0))`

You have to change three points:


- [ ] Change Line 66
https://github.com/Justinjay282/qwerty/blob/8eada18ae9a39f688a3757f1260ba9e5399c55e2/Kiosk_Main.py#L66
```
if self._counter > 0 and event.state == 0:  # reset the counter
```
- [ ] Add before Line 66
```
if event.state == 1:  # restart the counter
    event.state = 0
```
- [ ] Change line 26
https://github.com/Justinjay282/qwerty/blob/8eada18ae9a39f688a3757f1260ba9e5399c55e2/Kiosk_Main.py#L26
```
self.master.event_generate('<<IDLE>>', state=1, when='tail')
```

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I've commited the changes in `Kiosk_Main.py`, It's not counting when the `SplashScreen`I click and then it closed but it's permanently close. It's not counting after that one pop out

**Comment by WK-GiHu** [comment]
@Justinjay282 

You hava a indentation error, and i have updated to:
https://github.com/Justinjay282/qwerty/blob/8043ec8e633b68056c76dc4d3fb21bebf1220e35/Kiosk_Main.py#L65-L68

```
if event.state == 1: 
    self._counter = self.timeout 

elif self._counter > 0 and event.state == 0: 
     self._counter = self.timeout 
```

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, THANK YOU SO MUCH! It's done now. THANK YOU THANK YOU SO MUCH! I REALLY APPRECIATE YOUR HELP AND ALSO YOUR TEACHINGS. I"m gonna be honest It's hard for me to comprehend the Idle counter and the splash screen. But I understand the `FingerprintThread`and `RFIDThread` all thanks to you. I'll promise I'll never waste what you've taught me and after my thesis, I will focus on what you've teach me. I'm just so happy It's done now. I will now put the content in splash screen with the data from database to store the data even if the `Kiosk` is turned off. Again, Thank you so much! sorry for this long message I'm just so happy I can increase my sleep. ThankYOU!
