### ISSUE TITLE
Step 1: Split the whole into two files - App.py and VKeyboard.py

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#3]
@Justinjay282 

Split your whole script into two files:

1. `App.py` - All Application dependant, without virtual keyboard part.
2. `VKeyboard.py` - All virtual keyboard without any application part.

### Upload both, so i can review

**Comment by Justinjay282** [comment]
Hi sir, I'm done posting my code. I virtual keyboard code, It's only the two methods, the `def create` and `def select`. I put the `if __name__ == '__main__':` and the Tkinter entries to App.py.

**Comment by Justinjay282** [comment]
@WK-GiHu sir, I'm done posting my code. I separated the virtual keyboard code, It's only the two methods, the def create and def select. I put the if __name__ == '__main__': and the Tkinter entries to App.py.
