### ISSUE TITLE
Make new module 'FingerprintDevice.py'

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#30]
@Justinjay282 

- [x] Create a new `module` named `FingerprintDevice.py` and copy the whole `class FingerprintThread` from your last working module `Kiosk_Main.py` except the `mysql` part into it. Make it a `module` like `VKeyboard.py`.

- [x] Change `__init__` to `__init__(self, parent):`, without `callback`
https://github.com/Justinjay282/qwerty/blob/071a96586f79e9d8fd164c05c20a01bc6a4b0df4/Kiosk_Main.py#L11

- [x] Disable line 15, we move this line later and add `self.template = None`
https://github.com/Justinjay282/qwerty/blob/071a96586f79e9d8fd164c05c20a01bc6a4b0df4/Kiosk_Main.py#L15

- [x] Insert before line 41: `time.sleep(0.5)`
https://github.com/Justinjay282/qwerty/blob/071a96586f79e9d8fd164c05c20a01bc6a4b0df4/Kiosk_Main.py#L41

- [x] Change line 55 to `self.template = ...`
https://github.com/Justinjay282/qwerty/blob/071a96586f79e9d8fd164c05c20a01bc6a4b0df4/Kiosk_Main.py#L55

- [x] Insert after line 55
    ```
    self.app.event_generate('<<FINGERPRINT>>', when='tail')
    ```
- [x] Add the following test case after `if __name__ ...`
    ```
    import tkinter as tk
    
    def on_grant_access(event):
        print('on_grant_access()  positionNumber={},  accuracyScore={}'
            .format, fp.fingerprint[0], fp.fingerprint[1]))

    root = tk.Tk()
    fp = FingerprintThread(root)
    root.bind('<<FINGERPRINT>>', on_grant_access)
    root.mainloop()
    ```

**Comment by Justinjay282** [comment]
sir, @WK-GiHu , the file `FingerprintDevice.py` has been created in repository. Here's the error I've encountered.
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/pi/try.py", line 57, in run
    self.app.event_generate('<<FINGERPRINT>>', when='tail')
AttributeError: 'FingerprintThread' object has no attribute 'app'
```
but the fingerprint is running. it just stopped when the error occured.

**Comment by WK-GiHu** [comment]
@Justinjay282 

**Review `FingerprintDevice.py`**

- [ ] Remove line 3, no `mysql` in this module
  Remove line 5, no `tkinter` in this module
  https://github.com/Justinjay282/qwerty/blob/c4e91a0810c57a01faf40fc37c01cd6af6566683/FingerprintDevice.py#L3
https://github.com/Justinjay282/qwerty/blob/c4e91a0810c57a01faf40fc37c01cd6af6566683/FingerprintDevice.py#L5

- [ ] Duplicate `import time`, remove one
  https://github.com/Justinjay282/qwerty/blob/c4e91a0810c57a01faf40fc37c01cd6af6566683/FingerprintDevice.py#L4

- [ ] Change line 9 to `def __init__(self, app):` and add
  `self.app = app`
  https://github.com/Justinjay282/qwerty/blob/c4e91a0810c57a01faf40fc37c01cd6af6566683/FingerprintDevice.py#L9

- [ ] Remove the lines 17 to 19
https://github.com/Justinjay282/qwerty/blob/c4e91a0810c57a01faf40fc37c01cd6af6566683/FingerprintDevice.py#L17-L19

- [ ] Disable line 39, we know it's not blocking
https://github.com/Justinjay282/qwerty/blob/c4e91a0810c57a01faf40fc37c01cd6af6566683/FingerprintDevice.py#L39

- [ ] Remove all lines 59 to 74. The `'<GRANT_ACCESS>>'
` handling remains in `Kiosk.py` which we update after successfull running this module.
  https://github.com/Justinjay282/qwerty/blob/c4e91a0810c57a01faf40fc37c01cd6af6566683/FingerprintDevice.py#L59-L74

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I've edited the code `FingerprintDevice.py` and committed all the checklist above.
I'm encountering this error, Sir.
```
Exception in Tkinter callback

Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/try.py", line 61, in on_grant_access
    .format, fp.fingerprint[0], fp.fingerprint[1])
AttributeError: 'FingerprintThread' object has no attribute 'fingerprint'
```

**Comment by WK-GiHu** [comment]
@Justinjay282 

>the fingerprint scanner is running even if the error occurs.

Please be patient, you are one step ahead, she https://github.com/Justinjay282/qwerty/issues/31

>AttributeError: 'FingerprintThread' object has no attribute 'fingerprint'

- [ ] Remove line 7
https://github.com/Justinjay282/qwerty/blob/c5a09480d45530157cfd50f7f818ca773dcda059/FingerprintDevice.py#L7

- [ ] Change line 8 to: `FingerprintThread.result = None`
https://github.com/Justinjay282/qwerty/blob/c5a09480d45530157cfd50f7f818ca773dcda059/FingerprintDevice.py#L8

- [ ] Accordingly line 50 to: `FingerprintThread.result = ...`
https://github.com/Justinjay282/qwerty/blob/c5a09480d45530157cfd50f7f818ca773dcda059/FingerprintDevice.py#L50

- [ ] Change the test case in `__main__` to:
  ```
    import tkinter as tk

    def on_grant_access(event):
        fingerprint = FingerprintThread.template
        print('on_grant_access()  positionNumber={},  accuracyScore={}'
              .format, fingerprint[0], fingerprint[1])

    root = tk.Tk()
    FingerprintThread(root)
    root.bind('<<FINGERPRINT>>', on_grant_access)
    root.mainloop()
  ```

I want to know, if the test case in `__main__` is working before you continue with `Kiosk.py`. If OK, clos this Issue

**Comment by Justinjay282** [comment]
sir, @WK-GiHu, I also committed the changes here to `FingerprintDevice.py`
No error is occurring anymore sir.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>after scanning its printing `<built-in method format of str object at 0x75ed5020> -1 -1`

This is not the print statement from `def on_fingerprint`?
There is a typo, change to:
```
.format(fingerprint[0], fingerprint[1]))
```

**Comment by Justinjay282** [comment]
sir @WK-GiHu 

> @Justinjay282
> 
> ### Please, answer my questions
> I feel there is probably a logic error.
> Please explain what is `f.serarchTemplate()` doing?
> Which return value if NO template are found?
> 

It's responsible for searching for an image in the templates.
the `positionNumber = result[0]` will get what template number
if the template isn't registered to the fingerprint scanner it will return a value of -1
if there's a registered template it values is 1 to 1000


> > after scanning its printing `<built-in method format of str object at 0x75ed5020> -1 -1`
> 
> This is not the print statement from `def on_fingerprint`?
> There is a typo, change to:
> 
> ```
> .format(fingerprint[0], fingerprint[1]))
> ```

i've committed the changes and now printing the 
```
Waiting for finger...on_grant_access()  positionNumber=-1,  accuracyScore=-1
```

That's also the result of the scanned finger isn't registered in the fingerprint scanner; -1

**Comment by WK-GiHu** [comment]
@Justinjay282 

- [ ] Disabel line 7, line 46 and line 49
https://github.com/Justinjay282/qwerty/blob/d87798f4eeb58a02dba6ea94c957b8fc544d611a/FingerprintDevice.py#L7
https://github.com/Justinjay282/qwerty/blob/d87798f4eeb58a02dba6ea94c957b8fc544d611a/FingerprintDevice.py#L49
https://github.com/Justinjay282/qwerty/blob/d87798f4eeb58a02dba6ea94c957b8fc544d611a/FingerprintDevice.py#L46

- [ ] Add method: `def searchTemplate(self):`
  ```
  def searchTemplate(self):
      f.convertImage(0x01)
      return f.searchTemplate()
  ```

- [ ] Change to: `fp.searchTemplate()`
https://github.com/Justinjay282/qwerty/blob/d87798f4eeb58a02dba6ea94c957b8fc544d611a/FingerprintDevice.py#L57

- [ ] Change to: `fp = FingerprintThread(root)`
https://github.com/Justinjay282/qwerty/blob/d87798f4eeb58a02dba6ea94c957b8fc544d611a/FingerprintDevice.py#L62

Run module `FingerprintDevice.py`.

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I committed the changes in `FingerprintDevice.py`
I run it and receiving this error:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/Thesis/FingerprintDevice.py", line 60, in on_fingerprint
    fp.searchTemplate()
  File "/home/pi/Thesis/FingerprintDevice.py", line 53, in searchTemplate
    f.convertImage(0x01)
NameError: name 'f' is not defined
```

**Comment by WK-GiHu** [comment]
@Justinjay282 

>NameError: name 'f' is not defined

OK, you have to rename all `f.` to `self.f`

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I'm done renaming all `f` to `self.f` and did the `template = fp.searchTemplate()`
I'm having errors. 
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/Thesis/FingerprintDevice.py", line 60, in on_fingerprint
    template = fp.searchTemplate()
  File "/home/pi/Thesis/FingerprintDevice.py", line 53, in searchTemplate
    self.f.convertImage(0x01)
  File "/usr/lib/python3/dist-packages/pyfingerprint/pyfingerprint.py", line 802, in convertImage
    raise Exception('Unknown error '+ hex(receivedPacketPayload[0]))
Exception: Unknown error 0x20
```
```
device reports readiness to read but returned no data (device disconnected or multiple access on port?)
```
and
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/Thesis/FingerprintDevice.py", line 60, in on_fingerprint
    template = fp.searchTemplate()
  File "/home/pi/Thesis/FingerprintDevice.py", line 53, in searchTemplate
    self.f.convertImage(0x01)
  File "/usr/lib/python3/dist-packages/pyfingerprint/pyfingerprint.py", line 777, in convertImage
    receivedPacket = self.__readPacket()
  File "/usr/lib/python3/dist-packages/pyfingerprint/pyfingerprint.py", line 300, in __readPacket
    raise Exception('The received packet do not begin with a valid header!')
Exception: The received packet do not begin with a valid header!
```

These errors are not appearing simultaneously I also got successful data when I scanned a finger and it printed out the
```
print('on_grant_access()  positionNumber={},  accuracyScore={}'
              .format(template[0], template[1]))
```

**Comment by WK-GiHu** [comment]
@Justinjay282 

>Exception: The received packet do not begin with a valid header!

I didn't think this is related to the current changes.

Do you see the output of
https://github.com/Justinjay282/qwerty/blob/ba34247ddce9421799be8c405d638250ed341491/FingerprintDevice.py#L38
also?

**Comment by Justinjay282** [comment]
> @Justinjay282
> 
> > Exception: The received packet do not begin with a valid header!
> 
> I didn't think this is related to the current changes.

Yes, sir, it's not related I'm encountering this exactly this error when I just started doing fingerprint scanner. This error occurs if: 1. the wiring is wrong and 2. the USB converter is not working

> Do you see the output of
> https://github.com/Justinjay282/qwerty/blob/ba34247ddce9421799be8c405d638250ed341491/FingerprintDevice.py#L38
> 
> 
> also?

Here's the output.
on_grant_access()  positionNumber=4,  accuracyScore=132
actually it simultaneously appeared. 
this error
```
PyFingerprint:read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?), try 1 of 3
```
and this output
```
on_grant_access()  positionNumber=4,  accuracyScore=132
```
or not totally simultaneously but a couple of unnoticeable seconds gap...

**Comment by WK-GiHu** [comment]
@Justinjay282 

It's a timing issue, we have the background task force to wait until `def searchTemplate(self):` got processed.

- [ ] Ad after line 8: `self.continue = threading.Event()`
https://github.com/Justinjay282/qwerty/blob/ba34247ddce9421799be8c405d638250ed341491/FingerprintDevice.py#L8

- [ ] Add after line 50: 
https://github.com/Justinjay282/qwerty/blob/ba34247ddce9421799be8c405d638250ed341491/FingerprintDevice.py#L50
  ```
  self.continue.clear()
  self.continue.wait()
  ```

- [ ] Change line 54 to:
https://github.com/Justinjay282/qwerty/blob/ba34247ddce9421799be8c405d638250ed341491/FingerprintDevice.py#L54
  ```
  template = self.f.searchTemplate()
  self.continue.set()
  return template
  ```

**Comment by Justinjay282** [comment]
sir, @WK-GiHu, I've committed the changes in `FingerprintDevice.py`
I'm having a syntax error.
```
Traceback (most recent call last):
  File "/home/pi/Thesis/FingerprintDevice.py", line 9
    self.continue = threading.Event()
                ^
SyntaxError: invalid syntax
```

**Comment by WK-GiHu** [comment]
@Justinjay282 

>SyntaxError: invalid syntax

OK, `continue` is a Python reserved name.
- [ ] Change all `self.continue` to `self._continue`

- [ ] For readability change to: `...(on_fingerprint()  ...`
https://github.com/Justinjay282/qwerty/blob/87c4dc971274ef1d508b84998540ace40a9dc23e/FingerprintDevice.py#L66

**Comment by Justinjay282** [comment]
sir @WK-GiHu, It's now working.
but after continuously scanning I have this error
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/Thesis/FingerprintDevice.py", line 65, in on_fingerprint
    template = fp.searchTemplate()
  File "/home/pi/Thesis/FingerprintDevice.py", line 57, in searchTemplate
    template = self.f.searchTemplate()
  File "/usr/lib/python3/dist-packages/pyfingerprint/pyfingerprint.py", line 949, in searchTemplate
    raise Exception('Communication error')
Exception: Communication error
```

**Comment by WK-GiHu** [comment]
@Justinjay282 

>Exception: Communication error

OK, module `PyFingerprint` does not allow access from outside.
So we are off, no go!
I have to rethink about this ....

**Comment by Justinjay282** [comment]
sir @WK-GiHu, this is the tutorial I used.
https://tutorials-raspberrypi.com/how-to-use-raspberry-pi-fingerprint-sensor-authentication/

and also I relied on this since originally, the module was created by them.
https://github.com/bastianraschke/pyfingerprint/blob/Development/README.md

**Comment by WK-GiHu** [comment]
@Justinjay282 

Regarding to the souce of `pyfingerprint.py` the `Exception: Communication error` is related to the `template` data.

- [ ] Verify if the implemented `self._continue.wait()` works.
 Therefore, enable the line 33
https://github.com/Justinjay282/qwerty/blob/94be006dd78e20b2f1b488f218b93084c6073257/FingerprintDevice.py#L33
- [ ] Disable line 57 and line 58
https://github.com/Justinjay282/qwerty/blob/94be006dd78e20b2f1b488f218b93084c6073257/FingerprintDevice.py#L57-L58
- [ ] Add `print('_continue.set()')` after line 57


The `print(looping...)` should stop.

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I've committed the changes in `FingerprintDevice.py`
I only disable the `self._continue.set()` since it's having an error if I also disable the `template = ...`
after scanning a finger, the looping stopped also the fingerprint scanner.

**Comment by WK-GiHu** [comment]
@Justinjay282 

> it's having an error if I also disable the template = ...

Yes, the `return template` must also disabled

>after scanning a finger, the looping stopped also the fingerprint scanner.

Please confirm, `template = self.f.searchTemplate()` was called?
This means it's working now?

**Comment by Justinjay282** [comment]
@WK-GiHu sir,

>Yes, the `return template` must also disabled

I also disabled the `return template`
and receiving this error
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/Thesis/FingerprintDevice.py", line 68, in on_fingerprint
    .format(template[0], template[1]))
TypeError: 'NoneType' object is not subscriptable
```
But, I didn't disable the `template = ...` and `return template`
It scanned a finger then stopped working. no errors encountered.

>after scanning a finger, the looping stopped also the fingerprint scanner.

>Please confirm, `template = self.f.searchTemplate()` was called?
>This means it's working now?


Yes, I think it's working, but I didn't disable the  `template = ...` and `return template` then It scanned a finger then stopped working. no errors encountered.

I created a `FingerprintDevice_v1.py` for what I did above


Also, tried the `FingerprintDevice.py` (your pull request) 
its output is 
```
>>> Currently used templates: 5/1000
Waiting for finger...
```
no errors but I can't scan a finger.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>Yes, I think it's working, but I didn't disable the template = ... and return template then It scanned a finger the output is:
>`on_fingerprint()  positionNumber=4,  accuracyScore=116`
> then the scanner stopped working. no errors encountered.

OK, seems the previous `Exception: Communication error` are hardware related.
Remove the testing changes from this [comment](https://github.com/Justinjay282/qwerty/issues/30#issuecomment-598851101) the `._continue.wait()` is working.
Run again, to see if the `Exception ...` comes back.

---

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I got confused on what I'm gonna removed in `FingerprintDevice_v1.py` can you check if what I did is right? I just revert it back to original code, 
I enabled the `self._continue.set()`
and disable the `print('looping .readImage())` 
https://github.com/Justinjay282/qwerty/issues/30#issuecomment-598851101

**Comment by WK-GiHu** [comment]
@Justinjay282 

>can you check if what I did is right? I just revert it back to original code,

Yes, looks OK.

>after doing so the error comes back.

OK, I want to see **one** sequence output, therefore do:
https://github.com/Justinjay282/qwerty/blob/43330cfb5ccad5bfd1be98d6b6c6a7041be26e48/FingerprintDevice_v1..py#L56-L58
- [ ] Add before line 56: `print('before convertImage(1)')`
- [ ] Add before line 57: `print('before searchTemplate()')`
- [ ] Enable line 58

I want to see it from `Waiting for finger...` up to the `Exception`

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I've committed the changes above. 
Here's the output:
```
before convertImage(1)
before searchTemplate()
_continue.set()
on_fingerprint()  positionNumber=4,  accuracyScore=134
 ``
after scanning another finger there's an output and the communication error sir:
```
before convertImage(1)
before searchTemplate()
```
then an error:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/Thesis/FingerprintDevice.py", line 68, in on_fingerprint
    template = fp.searchTemplate()
  File "/home/pi/Thesis/FingerprintDevice.py", line 59, in searchTemplate
    template = self.f.searchTemplate()
  File "/usr/lib/python3/dist-packages/pyfingerprint/pyfingerprint.py", line 949, in searchTemplate
    raise Exception('Communication error')
Exception: Communication error
```

**Comment by WK-GiHu** [comment]
@Justinjay282 

### I'm missing the `'Waiting for finger...'` part

**Comment by Justinjay282** [comment]
> @Justinjay282
> 
> ### I'm missing the `'Waiting for finger...'` part

@WK-GiHu I'm sorry sir I didn't include it. But I edited my comment and include all the output

**Comment by WK-GiHu** [comment]
@Justinjay282 

Seems to working only **once**.
Please confirm, there are ony 2 times: `Waiting for finger...`?

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I tried it again sir, If I didn't remove my finger on the scanner and let it scan continuously, there are only to `Waiting for finger...?`. I tried it with a little bit interval, it became three. and I scan my finger for like every 1 or 2 seconds then no `communication error`

**Comment by WK-GiHu** [comment]
@Justinjay282 

>it became three. and I scan my finger for like every 1 or 2 seconds then no communication error

As i thought earlier, it's a timing issue ...
Does it harm you if we put a delay `time.sleep(1)` or `time.sleep(2)` before next `'Waiting for finger...'`?

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I think it will not harm. I think time.sleep(2) is actually quite fast because I scanned a finger with `time.sleep(2)`. two seconds is just not enough for the user to react or to remove the finger. The program is just way to fast.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>I've set it to time.sleep(2) I didn't remove the finger on the fingerprint scanner and there's still a communication error.

OK, stop here for now.
Continue with [issues/34#](https://github.com/Justinjay282/qwerty/issues/34#), let's verify `'REGISTER'`
