### ISSUE TITLE
Proposal FingerprintDevice.py from Pull Request

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#34]
Also, tried the `FingerprintDevice.py` (your pull request) 
 the `if self.f.verifyPassword()` is having a value error
```
The fingerprint sensor could not be initialized!
Exception message: The given fingerprint sensor password is wrong!
```
and changed it to `if self.f.verifyPassword()==False`
https://github.com/Justinjay282/qwerty/blob/00e3e4b710b2dbc52091caf5e6616c8946388402/FingerprintDevice.py#L37

no errors but I can't scan a finger.
The output is:
```
>>> Currently used templates: 5/1000
Waiting for finger...
```

_Originally posted by @Justinjay282 in https://github.com/Justinjay282/qwerty/issues/30#issuecomment-598990723_

**Comment by WK-GiHu** [comment]
@Justinjay282 

>and changed it to `if self.f.verifyPassword()==False`

OK, it's uncommon to do so, i wil investigage this later

>no errors but I can't scan a finger.
>The output is:
```
>>> Currently used templates: 5/1000
Waiting for finger...
```

- [ ] Add afttr line 17: `self._continue.set()`
https://github.com/Justinjay282/qwerty/blob/00e3e4b710b2dbc52091caf5e6616c8946388402/FingerprintDevice.py#L17

Retry

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I've committed the changes in `FingerprintDevice.py`. 
the loop `print('looping .readImage()')` is printing but receiving an error:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/pi/Thesis/FingerprintDevice_v2.py", line 75, in run
    self.f.app.event_generate('<<FINGERPRINT>>', when='tail', state=FingerprintThread.template[0])
AttributeError: 'PyFingerprint' object has no attribute 'app'
```

**Comment by WK-GiHu** [comment]
@Justinjay282 

>AttributeError: 'PyFingerprint' object has no attribute 'app'

It's my bad, but didn't you see the typo?
Should read 
```
self.app.event_generate('<<FINGERPRINT>>', when='tail', state=FingerprintThread.template[0])
```
also here
https://github.com/Justinjay282/qwerty/blob/43330cfb5ccad5bfd1be98d6b6c6a7041be26e48/FingerprintDevice.py#L92

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I'm so sorry sir, I didn't notice that when I re-read the code...

> 
> > AttributeError: 'PyFingerprint' object has no attribute 'app'
> 
> It's my bad, but didn't you see the typo?
> Should read
> 
> ```
> self.app.event_generate('<<FINGERPRINT>>', when='tail', state=FingerprintThread.template[0])
> ```
> 
> also here
> https://github.com/Justinjay282/qwerty/blob/43330cfb5ccad5bfd1be98d6b6c6a7041be26e48/FingerprintDevice.py#L92

It's working now, It's looping the `print(looping .readImage())` and if I scanned a finger it's output is :
```
on_fingerprint()  positionNumber=4
```

**Comment by WK-GiHu** [comment]
@Justinjay282 

>It's working now,

OK, we have to verify `REGISTER`, therefore enable
https://github.com/Justinjay282/qwerty/blob/43330cfb5ccad5bfd1be98d6b6c6a7041be26e48/FingerprintDevice.py#L109
by changeing to: `if 1:`

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I changed it to `if 1:` I tried it, it's registering the finger. I didn't notice that I'm adding a fingerprint in fingerprint scanner. I put a `print("registering finger")` when I started running the program. It's directing to the register. After registering It's detecting the template. re-run -> scan finger ->register -> scan again -> leads to continuous login.

**Comment by WK-GiHu** [comment]
@Justinjay282 

Your explanation is confusing me.
Please try to describe the problem only.

**Comment by Justinjay282** [comment]
sir @WK-GiHu, sorry sir if It's quite confusing.
There's no problem actually, sir. When I start running the code it starts with finger registration. after fingerprint registration, the continuous login is running.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>There's no problem actually

OK, do you think it's functional doing `REGISTER`?

>it starts with finger registration. after fingerprint registration, the continuous login is running

Yes, that's as it's running in `while ...` loop.
We need a notification, that the registering has finished and the user have to remove his finger before the next `Waiting for finger...`

**Comment by Justinjay282** [comment]
> @Justinjay282
> 
> > There's no problem actually
> 
> OK, do you think it's functional doing `REGISTER`?
> 

sir, @WK-GiHu, Yes I think it's functional... It's just not final but I think it'll work once completed.

> > it starts with finger registration. after fingerprint registration, the continuous login is running
> 
> Yes, that's as it's running in `while ...` loop.
> We need a notification, that the registering has finished and the user have to remove his finger before the next `Waiting for finger...`
> 
> Last step to verify:
> 
> * [ ]  Disable by `if 0:`
>   https://github.com/Justinjay282/qwerty/blob/e5974761d0b9401874fef569c4d65d91794a5b4f/FingerprintDevice.py#L106
> * [ ]  Enable by `if 1:` adding a valid position number
>   https://github.com/Justinjay282/qwerty/blob/e5974761d0b9401874fef569c4d65d91794a5b4f/FingerprintDevice.py#L114-L115

I did this and got an error
```
Traceback (most recent call last):
  File "/home/pi/Thesis/FingerprintDevice_v2.py", line 115, in <module>
    fp.delete_template('<position number to delete>')
  File "/home/pi/Thesis/FingerprintDevice_v2.py", line 25, in delete_template
    b = self.f.deleteTemplate(str(positionNumber))
  File "/usr/lib/python3/dist-packages/pyfingerprint/pyfingerprint.py", line 1016, in deleteTemplate
    if ( positionNumber < 0x0000 or positionNumber >= capacity ):
TypeError: '<' not supported between instances of 'str' and 'int'
```
I changed the `positionNumber` to str but the error still appears.

**Comment by WK-GiHu** [comment]
@Justinjay282 

Update or show this line
https://github.com/Justinjay282/qwerty/blob/0624fe771260a188cfcc1876056dc4590bd1bb4e/FingerprintDevice.py#L115

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I didn't change the `'<position number to delete>'
https://github.com/Justinjay282/qwerty/blob/7a2e5ea275aa0307f56051c5b6fb11694ff4d48a/FingerprintDevice.py#L115
 I changed it to template number and it works. The template got deleted.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>I changed it to template number and it works. The template got deleted.

OK, explain this statement
https://github.com/Justinjay282/qwerty/blob/967a2bd2cf7920cedf2c9240a503b131da180e7d/FingerprintDevice.py#L84

**Comment by Justinjay282** [comment]
> @Justinjay282
> 
> > I changed it to template number and it works. The template got deleted.
> 
> OK, explain this statement
> https://github.com/Justinjay282/qwerty/blob/967a2bd2cf7920cedf2c9240a503b131da180e7d/FingerprintDevice.py#L84

sir @WK-GiHu, I actually I didn't use that statement I just didn't notice it so I forgot to delete it. All I know is that statement will get the characteristic of the image saved in the fingerprint scanner, after that It can be converted as hexadecimal to use as a reference code for DB, etc.

**Comment by WK-GiHu** [comment]
@Justinjay282 

> I actually I didn't use that statement

Ok, remove this line

---

- [ ] Insert after line 85 to wait after registering
 https://github.com/Justinjay282/qwerty/blob/967a2bd2cf7920cedf2c9240a503b131da180e7d/FingerprintDevice.py#L85
  ```
            self._continue.clear()
            self._continue.wait()
  ```
- [ ] Disabel line 93 `# `
  https://github.com/Justinjay282/qwerty/blob/967a2bd2cf7920cedf2c9240a503b131da180e7d/FingerprintDevice.py#L93

Prepare for testing `'REGISTER'`
- [ ] Enable
 https://github.com/Justinjay282/qwerty/blob/967a2bd2cf7920cedf2c9240a503b131da180e7d/FingerprintDevice.py#L106
- [ ] Insert after line 106: `fp._continue.set()`

- [ ] Disable
https://github.com/Justinjay282/qwerty/blob/967a2bd2cf7920cedf2c9240a503b131da180e7d/FingerprintDevice.py#L114
- [ ] Move the code block before line 114
https://github.com/Justinjay282/qwerty/blob/967a2bd2cf7920cedf2c9240a503b131da180e7d/FingerprintDevice.py#L106-L108

Run test `'REGISTER'`
**Note**: It will register only once per running `__main__`!

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I run it and after scanning a finger twice it stopped running. I run again and a template has been added. Also committed the changes above.

**Comment by WK-GiHu** [comment]
@Justinjay282 

After reviewing, it looks bad, we are loosing the event.
Please explain which behavior do you want if the registering **fails**, means the two templates doesn't match.

**Comment by Justinjay282** [comment]
sir @WK-GiHu, there are two behaviors if the registration fails. If the finger already exists and if the two scanned fingers do not match.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>here are two behaviors if the registration fails

OK, explain which behavior do you want.
How does the retry look like?

1. case
>If the finger already exists 

2. case
>if the two scanned fingers do not match.

**Comment by Justinjay282** [comment]
sir @WK-GiHu, at the first scan of the finger the program can immediately detect if this fingerprint already exists. Then a `message box` will appear saying `Fingerprint already registered` then the user can register another finger that is not registered yet.
In case 2, if the scanned fingers do not match there's also a `messagebox` then after that, It's back to the registration of the first finger again then scan 2nd finger if match then registered if not then go back to scan finger again.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>at the first scan of the finger the program can immediately detect if this fingerprint already exists. Then a message box will appear saying Fingerprint already registered then the user can register another finger that is not registered yet.

Message box within `Thread.run()` is bad.

We go with send event `fail == -1/-2` in both cases
Which allows to restart registering.
I have to redesign `Fingerprint.py`, take a while...
In the meantime you can try to implement accordingly to `__main__`, in `Kiosk.py` the **Login** part.

**Comment by Justinjay282** [comment]
@WK-GiHu, Thank you so much, sir.
I'm doing it on Login part on my `Kiosk.py` It's working well without the registration. same with the RFID Scanner. It's also passing the right value of the template to the database.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>I did
>
>if sequence == 1:
>    self.f.convertImage(1)

Didn't you note: ***I have to redesign Fingerprint.py, take a while...***
Now this get overwriten from the Pull Request.

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I noted it, sir, I'm just trying things and re-reading the code since I am dumb and I'm doing my best to understand all these things. I just updated you on what I'm doing, sir, hehe...

**Comment by WK-GiHu** [comment]
@Justinjay282 

OK, go ahead and get the Pull Request
**Note**: I have change this again:
https://github.com/Justinjay282/qwerty/blob/198fb85e3e3df0c388e9c57cfd6e7ae9fa03dc61/FingerprintDevice.py#L37

Run all tests

1. Login
2. Register with allready enrolled template
2.1 Register which will fail `compareCharacteristics`
2.2 Register valid
3. Delete template

**Comment by Justinjay282** [comment]
Sir @WK-GiHu, It's working sir, but when I do. login, delete 3 times I got an error
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 501, in read
    'device reports readiness to read but returned no data '
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/Thesis/FingerprintDevice_v2.py", line 144, in on_delete
    fp.delete_template(template_id)
  File "/home/pi/Thesis/FingerprintDevice_v2.py", line 32, in delete_template
    b = self.f.deleteTemplate(int(positionNumber))
  File "/usr/lib/python3/dist-packages/pyfingerprint/pyfingerprint.py", line 1014, in deleteTemplate
    capacity = self.getStorageCapacity()
  File "/usr/lib/python3/dist-packages/pyfingerprint/pyfingerprint.py", line 1228, in getStorageCapacity
    return self.getSystemParameters()[2]
  File "/usr/lib/python3/dist-packages/pyfingerprint/pyfingerprint.py", line 536, in getSystemParameters
    receivedPacket = self.__readPacket()
  File "/usr/lib/python3/dist-packages/pyfingerprint/pyfingerprint.py", line 285, in __readPacket
    receivedFragment = self.__serial.read()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 509, in read
    raise SerialException('read failed: {}'.format(e))
serial.serialutil.SerialException: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
```

**Comment by WK-GiHu** [comment]
@Justinjay282 

> I got an error

These are the allready known hardware/wireing issues.
Check, hardwar and wires.

There are no changes in  `def delete_template(template_id)` .

**Comment by Justinjay282** [comment]
sir, @WK-GiHu yes, I just encountered a different error the wiring. I think we have to do something about the wire.
the code is working sir. If the finger didn't match the value is `-2` if the finger is already registered it's `-1` and for the login, if the finger is registered Its value is >=0 then if not registered also `-1`

**Comment by WK-GiHu** [comment]
@Justinjay282 

OK, close this issue and this [issues/30](https://github.com/Justinjay282/qwerty/issues/30)

Reopen [issues/31](https://github.com/Justinjay282/qwerty/issues/31) and adapt the last changes to get **Login** working.

**Comment by Justinjay282** [comment]
sir @WK-GiHu Okay sir thank you so much. I closed [issues/30](https://github.com/Justinjay282/qwerty/issues/30) will also close this one as well.

I'll also go offline now, and I will get some rest. You sir also take a good rest and take care.
