### ISSUE TITLE
Stop mixing module

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#37]
@Justinjay282 

You are starting to mixing modules.
https://github.com/Justinjay282/qwerty/blob/f1c29403c15059e3407258875640a3c7e054a83f/Kiosk_Main.py#L8
https://github.com/Justinjay282/qwerty/blob/f1c29403c15059e3407258875640a3c7e054a83f/update_resident_fingerprint.py#L7

### Please cleanup, stay with module name `FingerprintDevice.py`
Rename the other, no longer used versions instead.
I want to see only
```
from FingerprintDevice import FingerprintThread
```
Do this at once, can't continue ...

**Comment by Justinjay282** [comment]
Hi sir @WK-GiHu, I'm so sorry about this. I've edited the code with correct import.
