### ISSUE TITLE
create login system using tkinter controller

### ISSUE THREAD

**Issue by Justinjay282** [Justinjay282/qwerty#40]
Hi, sir @WK-GiHu, I'm revising my admin system and I want to create an admin system using a controller (to avoid memory leak). so far I'm doing good.
but the thing is when I logged in successfully, I can't display the details from the database.

I used `shared data` to pass the value of the username and password using controller:
```
self.shared_data = {"username": StringVar(),
                            "password": StringVar()
                           }
```
It's working, however, when I logged in successfully I can't get the value from the database.

here's my method when I clicked the login button
```
def submit_login(self):
        username = self.controller.shared_data["username"].get()
        password = self.controller.shared_data["password"].get()
        self.cursor.execute("SELECT * FROM residents_admin WHERE USERNAME = %s AND PASSWORD = %s", (username, password))
        if self.cursor.fetchone() is not None:
            messagebox.showinfo("Success", "Welcome")
            self.controller.show_frame("Main_Page")
        elif username =="" or password =="":
            messagebox.showerror("Notice!", "Please input password and username")
        else:
            messagebox.showerror("Notice!", "username or password is incorrect")
```
It's also working, if I logged in correctly. this is my code after successful login:
```
class Main_Page(Frame):
    def __init__(self, parent, controller):
        Frame.__init__(self, parent)
        self.controller = controller
        
        username = self.controller.shared_data["username"].get()
        password = self.controller.shared_data["password"].get()
        print(username, password)
        self.cursor.execute("SELECT * FROM residents_admin WHERE USERNAME = %s AND PASSWORD = %s",(username, password))
        self.data = self.cursor.fetchone()

        print(self.data)
        #display GUI
```
 but the thing is when I've logged in successfully. I can't get any value from `self.controller.share_data["username"].get()` and self.controller.share_data["username"].get() and also, from the database which is the `self.data = self.cursor.fetchone()` the result of print is `None`
I've added the code in repository so you can check sir if I did something wrong.

Earlier, my adviser checks the program we've created. I think the result is much better than last time.
The changes I'm not confident to do is to shift the RFID login to RFID register just like what we did to the fingerprint scanner. But I'll do my best to do it. This is actually because of you why I've made it this far.

**Comment by WK-GiHu** [comment]
@Justinjay282 

https://github.com/Justinjay282/qwerty/blob/a6a15d10ff8fa7a9db1e276bf55905911f0690f6/admin_system_controller#L12

If you import this into `Kiosk_Main` this leads to unexpected behavior!
Read [Why are multiple instances of Tk discouraged?](https://stackoverflow.com/questions/48045401/why-are-multiple-instances-of-tk-discouraged)

---

> the result of print is `None`

https://github.com/Justinjay282/qwerty/blob/a6a15d10ff8fa7a9db1e276bf55905911f0690f6/admin_system_controller#L107-L113

**BIG NOGO**, you are doing **all** within `__init__`.
`__init__` is excuted **only once**, here at the codeline 39, far before you ever typed in anything. So it's useless, which explains the `None` result.

https://github.com/Justinjay282/qwerty/blob/a6a15d10ff8fa7a9db1e276bf55905911f0690f6/admin_system_controller#L39

You need to update your `Main_Page` widgets before or at switching to it:
Read [How would I make a method which is run every time a frame is shown in tkinter](https://stackoverflow.com/q/35029188/7432)

**Comment by Justinjay282** [comment]
sir @WK-GiHu, It works thank you so much! However, When I logged in for the first time successfully it's okay, but when I clicked log out then log in again, there are two frames in one window.
Here's the output of my GUI at first try:
![image](https://user-images.githubusercontent.com/59200116/77811274-43bc1a00-70d4-11ea-8414-a5654f8770fa.png)

Here's the output for the second time login:
![image](https://user-images.githubusercontent.com/59200116/77811284-5a627100-70d4-11ea-80a8-abfbc406bcfa.png)

in my `self._logout` method I have this
``` 
def _logout(self):
        self.controller.show_frame("Login_Page")
        self.controller.shared_data["password"].set("")
```

**Comment by Justinjay282** [comment]
sir @WK-GiHu, It works thank you so much! However, When I logged in for the first time successfully it's okay, but when I clicked log out then log in again, there are two frames in one window.
Here's the output of my GUI at first try:
image
![image](https://user-images.githubusercontent.com/59200116/77811456-626ee080-70d5-11ea-9855-33582d34d095.png)

Here's the output for the second time login:
image
![image](https://user-images.githubusercontent.com/59200116/77811505-ba0d4c00-70d5-11ea-995a-0bfdc975672f.png)


in my self._logout method I have this

def _logout(self):
        self.controller.show_frame("Login_Page")
        self.controller.shared_data["password"].set("")

the background on the second login disappeared and a new frame appeared.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>log in again, there are two frames in one window.

This event get also fired if switching to `Login_Page`. 
It's harmless, if you **only** update widgets in `def on_show_frame` and handle possible `None` values. 
https://github.com/Justinjay282/qwerty/blob/94aed158fe1d0d074e7e06bfc98eb65447fa8c0e/admin_system_controller#L51

---

Whithin `def on_show_frame`, do only **update** widgets **not create new one**.
https://github.com/Justinjay282/qwerty/blob/94aed158fe1d0d074e7e06bfc98eb65447fa8c0e/admin_system_controller#L181


That's wrong, on every event `'ShowFrame'` you create new widgets. This leads to stacking widgets.
https://github.com/Justinjay282/qwerty/blob/94aed158fe1d0d074e7e06bfc98eb65447fa8c0e/admin_system_controller#L192

**Comment by Justinjay282** [comment]
sir @WK-GiHu,
> The implementation from Bryan is not page sensitive, should be improved, e.g.
so I just need to add `event = None`?
I'm sorry, I'm actually clueless on how to improve this sir...

> That's wrong, on every event `'ShowFrame'` you create new widgets. This leads to stacking widgets.
> https://github.com/Justinjay282/qwerty/blob/94aed158fe1d0d074e7e06bfc98eb65447fa8c0e/admin_system_controller#L192

 I can't quite get this. if I put the widgets from `def on_show_frame` 
I'll receive an error:
```
    self.full_name = (self.data[1] + "," + " " + self.data[3] + " " + self.data[2])
AttributeError: 'Main_Page' object has no attribute 'data'
```

**Comment by WK-GiHu** [comment]
@Justinjay282 

>The implementation from Bryan is not page sensitive, should be improved,

I'm wrong, don't change anything. You have bound to the `Frame`:
https://github.com/Justinjay282/qwerty/blob/94aed158fe1d0d074e7e06bfc98eb65447fa8c0e/admin_system_controller#L179

---

- [ ] Move the following lines 192 to 205 into `__init__`.
**Set all `text=None`**!

https://github.com/Justinjay282/qwerty/blob/94aed158fe1d0d074e7e06bfc98eb65447fa8c0e/admin_system_controller#L192-L205

---

### In `def on_show_frame(...`

- [ ] Update **all** `Label.text` accordinly:
```
self.profile_name.configure(text=self.full_name)
```
- [ ] Do the above accordinly for every `Label`

**Comment by Justinjay282** [comment]
OMG sir @WK-GiHu, it worksss. Thank you so much! :)
Is this also applicable to treeview? I also have the same situation using `ttk.treeview` everytime I put the `display db in treeview` It's also stacking up on every click.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>Is this also applicable to treeview?

I didn't see any `Treeview` in [admin_system_controller](https://github.com/Justinjay282/qwerty/blob/master/admin_system_controller)?

You should follow this rules:
- Every static GUI definition have to be done in `__init__`
- Every data that are not avail at `__init__` runtime, have to be set to `None` or no data have to be inserted at all.
- At `ShowFrame`, update the widgets
  - `.configure(text=`
  - `<entry>.delete(0, tk.END) ; <entry>.insert(0. <data>)` or if you want to append without `.delete`
  - `<treeview>.delete(.... ; <treeview>.insert(...` or append only.

**Comment by Justinjay282** [comment]
sir @WK-GiHu, Thankyou so much for your explanation sir :). 
I'll keep this in my mind and these are very helpful. 
I'll go and try the `<entry>.delete(0, tk.END) ; <entry>.insert(0. <data>)` than my solution having many `var.set("")` is not very efficient.

I've also edited the [admin_system_controller] and put the `Treeview`. I didn't do it in my main code since it'll stack up the data in my `Treeview`. I also look at `Treeview` documentation. I really need to learn how to understand what's in the documentation because it's really hard for me to comprehend such things, the reason I can't find a better solution for my problem...

**Comment by WK-GiHu** [comment]
@Justinjay282 

pleased Close If this issued ist solved
