### ISSUE TITLE
def on_update_treev_user

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#42]
@Justinjay282 

https://github.com/Justinjay282/qwerty/blob/87d814bdf87ecb6669adce77bd635a9f25086d92/admin_system_controller#L316

Does this work?
The enclosing `(...)` are redundant, `data` is allready a sequence
Furthermore, your `Treeeview` Columns count (10), is not in sync with the fetched fields.

**Comment by Justinjay282** [comment]
sir @WK-GiHu, It's working but every time I pressed `back button` then `click the `display treeview button` again the displayed data is stacking up.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>data is stacking up.

If you don't need to reloadt, add the following condition:
```
if not self.tree.get_children():
    # Do query and populate in `Treeview`
    ...
else:
    # Allready populated
    pass
```
If you need to reload, delete before click the display treeview button
```
self.tree.delete(*self.tree.get_children())
```

**Comment by Justinjay282** [comment]
sir @WK-GiHu, SIRRR! Thank you so much! :) sir I'm having an error. I created a `class Change_Password` It's working actually. If I changed the password of an admin. It's good. but when I clicked the `logout button` I'm receiving this error.

```
Traceback (most recent call last):
  File "D:\SchoolApp\Python\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "d:/admin_system_pc/admin_system_revised.py", line 212, in on_get_login_details
    self.full_name = (self.data[1] + "," + " " + self.data[3] + " " + self.data[2])
TypeError: 'NoneType' object is not subscriptable
```
I edited the code [admin_system_controller] and put `class Change_Password`
