### ISSUE TITLE
class Change_Password TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#43]
I'm having an error. I created a `class Change_Password` It's working actually. If I changed the password of an admin. It's good. but when I clicked the `logout button` I'm receiving this error.

```
Traceback (most recent call last):
  File "D:\SchoolApp\Python\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "d:/admin_system_pc/admin_system_revised.py", line 212, in on_get_login_details
    self.full_name = (self.data[1] + "," + " " + self.data[3] + " " + self.data[2])
TypeError: 'NoneType' object is not subscriptable
```
I edited the code [admin_system_controller] and put `class Change_Password`

_Originally posted by @Justinjay282 in https://github.com/Justinjay282/qwerty/issues/42#issuecomment-605866781_

**Comment by WK-GiHu** [comment]
@Justinjay282 

I assume you are refering to:
https://github.com/Justinjay282/qwerty/blob/4e8ad4c4ca6f4e3447eeec3d4d7edc2ba326df50/admin_system_controller#L413-L415

>`TypeError: 'NoneType' object is not subscriptable`

This means `data` is `None`, probably wrong `password` or/and `username`.

>If I changed the password of an admin

Verify if you get the expected data from:
https://github.com/Justinjay282/qwerty/blob/4e8ad4c4ca6f4e3447eeec3d4d7edc2ba326df50/admin_system_controller#L409-L410

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I tried it and I'm getting the expected data. The login is still correct and even the details.

**Comment by WK-GiHu** [comment]
@Justinjay282 

> I'm getting the expected data. 

https://github.com/Justinjay282/qwerty/blob/4e8ad4c4ca6f4e3447eeec3d4d7edc2ba326df50/admin_system_controller#L412

Then you have to verify if the `password/username` pair is realy in `residents_admin`

---

>The login is still correct and even the details. I'm getting an error, every time I changed the password and then use it to login again. then after that. without closing the program and if I continue using it. No error is occurring.

Did you obey to `commit` after update the `password`?

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I have `self.db.autocommit(True)` then also added the `self.db.commit()` on `change password` but It's still the same.

the `Traceback` this line is the error.
https://github.com/Justinjay282/qwerty/blob/4e8ad4c4ca6f4e3447eeec3d4d7edc2ba326df50/admin_system_controller#L191

I even modified the `self.full_name` and separated it into different variables. but still the same

**Comment by WK-GiHu** [comment]
@Justinjay282 

>the Traceback this line is the error.

Verify the codeflow:

1. `Main_Page.on_show_frame` is called from 
  https://github.com/Justinjay282/qwerty/blob/4e8ad4c4ca6f4e3447eeec3d4d7edc2ba326df50/admin_system_controller#L93
  There you have allready done a successfully
  https://github.com/Justinjay282/qwerty/blob/4e8ad4c4ca6f4e3447eeec3d4d7edc2ba326df50/admin_system_controller#L96

2. Why do you reconnect here?
  https://github.com/Justinjay282/qwerty/blob/4e8ad4c4ca6f4e3447eeec3d4d7edc2ba326df50/admin_system_controller#L185-L186
    - [ ] Don't know, then disable for testing
  Should it be in general only done **once**, here?
  https://github.com/Justinjay282/qwerty/blob/4e8ad4c4ca6f4e3447eeec3d4d7edc2ba326df50/admin_system_controller#L15-L16
    - [ ] Because i reconnect ...

**Comment by Justinjay282** [comment]
sir @WK-GiHu 

> @Justinjay282
> 
> > the Traceback this line is the error.
> 
> Verify the codeflow:
> 
> 1. `Main_Page.on_show_frame` is called from

Yes it's called when the method `submit_login` was clicked.
 https://github.com/Justinjay282/qwerty/blob/4e8ad4c4ca6f4e3447eeec3d4d7edc2ba326df50/admin_system_controller#L93
>    
>    There you have allready done a successfully
>    https://github.com/Justinjay282/qwerty/blob/4e8ad4c4ca6f4e3447eeec3d4d7edc2ba326df50/admin_system_controller#L96

so data to be gathered here are the one to be passed on `controller.shared_data[]`?
no need to select again?

> 2. Why do you reconnect here?
>    https://github.com/Justinjay282/qwerty/blob/4e8ad4c4ca6f4e3447eeec3d4d7edc2ba326df50/admin_system_controller#L185-L186
>    

I deleted this sir, no need to reconnect again.

>    * [ ]  Don't know, then disable for testing
>      Should it be in general only done **once**, here?
>      https://github.com/Justinjay282/qwerty/blob/4e8ad4c4ca6f4e3447eeec3d4d7edc2ba326df50/admin_system_controller#L15-L16
>    * [ ]  Because i reconnect ...

I put it there so I'll not pass the `self.db` to the controller, since It isn't accessible to another class.

**Comment by WK-GiHu** [comment]
> It's solved now

OK
