### ISSUE TITLE
declared another `toplevel` window

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#7]
sir @WK-GiHu, I declared another `toplevel` window, `var = Toplevel()` and then `VKeyboard(var)` is it able? 

_Originally posted by @Justinjay282 in https://github.com/Justinjay282/qwerty/issues/1#issuecomment-584659847_

**Comment by WK-GiHu** [comment]
@Justinjay282 

>another toplevel window, `var = Toplevel()` and then `VKeyboard(var)`

You are missing the parent in `Toplevel()`
Update or add a new file, so i can review.

> is it able?

I assume you don't have to instantiate a new `VKeyboard` for every `Toplevel`.
One thing to obey, a `Toplevel` grabs key events, you have to try if this will prevent the **main** `VKeyboard` to work.

**Comment by Justinjay282** [comment]
Hi sir, @WK-GiHu , I'm slowly understanding it. I'm doing it now, but I have a question, the default color of my `widgets` are gray, how can I change it to `white`?

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I just want to ask how to fix the error
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/Desktop/VKeyboard.py", line 28, in on_event
    if w.master is not self:
AttributeError: 'str' object has no attribute 'master'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/Desktop/VKeyboard.py", line 28, in on_event
    if w.master is not self:
AttributeError: 'str' object has no attribute 'master'
```
everytime I will click to `combobox` I'm receiving an error. I've created a new file named `registration.py` so you can check. Thank you! :)
