### ISSUE TITLE
the default color of my `widgets` are gray, how can I change it to `white`?

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#8]
Hi sir, @WK-GiHu , I'm slowly understanding it. I'm doing it now, but I have a question, the default color of my `widgets` are gray, how can I change it to `white`?

_Originally posted by @Justinjay282 in https://github.com/Justinjay282/qwerty/issues/7#issuecomment-585006718_

**Comment by WK-GiHu** [comment]
@Justinjay282 

Read [possible-to-have-a-standard-style](https://stackoverflow.com/questions/52210391/is-it-possible-to-have-a-standard-style-for-a-widget/52210978#52210978)

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, thank you, thank you so much. another reference to help me finish my thesis. Thank you :)
