### ISSUE TITLE
AttributeError: 'str' object has no attribute 'master'

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#9]
sir @WK-GiHu, I just want to ask how to fix the error
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/Desktop/VKeyboard.py", line 28, in on_event
    if w.master is not self:
AttributeError: 'str' object has no attribute 'master'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/Desktop/VKeyboard.py", line 28, in on_event
    if w.master is not self:
AttributeError: 'str' object has no attribute 'master'
```
everytime I will click to `combobox` I'm receiving an error but the program itself is working continuesly. I've created a new file named `registration.py` so you can check. Thank you! :)

_Originally posted by @Justinjay282 in https://github.com/Justinjay282/qwerty/issues/7#issuecomment-585060296_

**Comment by WK-GiHu** [comment]
@Justinjay282 

>AttributeError: 'str' object has no attribute 'master'

The reason is a special behavior of a `.Combobox` widget.
See and merge my [`Pull request`](https://github.com/Justinjay282/qwerty/pull/10)

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I got it, thank you so much for helping me understand this. I'm slowly getting it I'm so happy. I'm doing another module for `update module`. I will update the issue you created about `top level` sir :) Again, thank you much. I don't know how to repay you, if you also have a favor you can also ask me. I know you don't need me but I will do my best to help you back, if there's any help I can do. Thank you so much :)

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I've put 2 `py files` in `codes` named `register_user.py` and `Kiosk.py` this error is quite similar to the previous one since it's not altering how my main program works. I have a `start page` there's a login button there. after login I'll proceed to main menu, which is there's a lot of buttons. When I'm clicking the back button, there's no error. If I clicked the `register user` the button is calling a `registration module` after typing some and go back to `main page` then if i clicked `back to login` it's showing me this error.
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/Thesis/VKeyboard.py", line 41, in on_event
    super().withdraw()
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1995, in wm_withdraw
    return self.tk.call('wm', 'withdraw', self._w)
_tkinter.TclError: bad window path name ".!registration_user.!vkeyboard"
```

**Comment by WK-GiHu** [comment]
@Justinjay282 

If the **topic** issue are fixed, please `[Close]` this issue.
